name: Build v8a Release APK (Guaranteed)

on:
  workflow_dispatch:

jobs:
  build-android-release-v8a:
    runs-on: ubuntu-latest
    
    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v4

      - name: ✅ Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      - name: ✅ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 🔑 关键步骤1：生成临时签名文件
      - name: ✅ Create Temporary Keystore
        id: create_keystore
        run: |
          KEYSTORE_PATH="${GITHUB_WORKSPACE}/android/app/upload-keystore.jks"
          keytool -genkey -v \
            -keystore "${KEYSTORE_PATH}" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias upload \
            -storepass android \
            -keypass android \
            -dname "CN=GitHub Actions, OU=CI, O=Auto Build, L=Cloud, S=Online, C=US"
          echo "keystore_path=${KEYSTORE_PATH}" >> $GITHUB_OUTPUT

      # 🔑 关键步骤2：创建key.properties（使用绝对路径，100%可靠）
      - name: ✅ Create key.properties with Absolute Path
        run: |
          cat > android/key.properties << EOF
          storeFile=${{ steps.create_keystore.outputs.keystore_path }}
          storePassword=android
          keyPassword=android
          keyAlias=upload
          EOF
          
          echo "=== Generated key.properties ==="
          cat android/key.properties
          echo "=== Verify keystore exists ==="
          ls -lh "${{ steps.create_keystore.outputs.keystore_path }}"

      - name: ✅ Get Flutter Dependencies
        run: flutter pub get

      - name: ✅ Build arm64-v8a Release APK
        run: |
          flutter build apk --release \
            --target-platform android-arm64 \
            --build-name=1.0.0 \
            --build-number=$((GITHUB_RUN_NUMBER + 10))

      - name: ✅ Verify Build Output
        run: |
          echo "=== APK File Info ==="
          ls -lh build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          file build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: 📦 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          if-no-files-found: error